#!/bin/bash
se=$(echo -e "poweroff\nreboot\ntty" | dmenu $@ -p 'exit')
if [ "$se" = "poweroff" ]; then
	systemctl poweroff
elif [ "$se" = "reboot" ]; then
	systemctl reboot
elif [ "$se" = "tty" ]; then
	pkill dwm
fi
